POST http://localhost:5293/breakfasts
Content-Type: application/json

{
    "name": "Bread",
    "description": "food food food food food humm fooooood humm fooooood",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###

GET http://localhost:5293/breakfasts/dab08473-0f28-404c-bfa9-8577e5fd3ab5